pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('pizzas', views.pizzas, name = 'pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name = 'pizza'),
    path('new_comment/<int:pizza_id>', views.new_comment, name = 'new_comment'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name = 'register'),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length = 50)
    picture = models.ImageField(upload_to = 'img', null = True, blank = True)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    topping_name = models.CharField(max_length = 50)

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs = {'cols': 80})}

pizzas/views.py
from django.shortcuts import render, redirect

from .models import Pizza, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()
    
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    toppings = pizza.topping_set.all().order_by('pizza')
    comments = pizza.comment_set.all().order_by('-date_added')
    picture = Pizza.picture
    
    context = {'pizza': pizza, 'toppings':toppings, 'comments': comments, 'picture': picture}
    return render(request, 'pizzas/pizza.html', context)

@login_required
def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data = request.POST)

        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.pizza = pizza
            new_comment.owner = request.user
            new_comment.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id = pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_comment.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('pizzas:index')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>El Gage-o's Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">El Gage-o's Pizzeria</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" 
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>   
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'pizzas:pizzas'%}">Pizzas</a></li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <span class="navbar-text"}">Hello, {{ user.username }}.</span>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a></li>
                {% endif %}
              </ul>
            </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>            
    </main>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Pizza for pizza lovers.</h1>

        <p class="lead">El Gage-o's pizzeria is proud to bring you authentic Italian pizza
            with the freshest ingredients and the most high-quality cheeses. We pride ourselves
            on the simplicity of our menu, created at the highest level.
        </p>

        <p>
            {% load static %} 
            <img src="{% static 'logo/Pizzeria-Logo.jpeg' %}" alt="logo" />
        </p>

        <p class="lead">Disclaimer: The pizzas are not topped with knives and forks as the image would suggest.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new comment:</h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </p>

    <form action="{% url 'pizzas:new_comment' pizza.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add Comment</button>
    </form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block page_header %} 
    <h2>{{ pizza }}</h2>
{% endblock page_header %}

{% block content %}


<p><h3>Toppings</h3></p>

<ul>
    {% for t in toppings %}
    <li>
        <p><h4>{{ t.topping_name }}</h4></p>
    </li>
    {% empty %}
        <li><h4>This pizza has no toppings.</h4></li>
    {% endfor %}
</ul>

<p>
    <img src="{{ pizza.picture.url }}">
</p>

<p><h3>Comments</h3></p>

<ul>
    {% for c in comments %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ c.owner }} on {{ c.date_added|date:'M d, Y H:i' }}
            </h4>

            <div class="card-body">
                {{ c.text|linebreaks }}
            </div>
        </div>

    {% empty %}
        <li>No one has commented on this pizza yet.</li>
    {% endfor %}
</ul>

<p>
    {% if user.is_authenticated %}
        <a href="{% url 'pizzas:new_comment' pizza.id %}">Leave a Comment</a>
    {% else %}
        <a href="{% url 'users:login' %}">Leave a Comment</a>
    {% endif %}
</p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block page_header %} 
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<p>Pizza Menu</p>

<ul>
    {% for p in pizzas %}
        <li><h3>
            <li><a href="{% url 'pizzas:pizza' p.id %}">{{ p.pizza_name }}</a></li>
        </h3></li>
    {% empty %}
        <li><h3>There are no pizzas on the menu.</h3></li>
    {% endfor %}
</ul>

{% endblock content %}